resize_shape: [256, 256]
targets: ['Fire_Images']
model_file_paths: ["fire_cnn_classifier_layers.json", "fire_cnn_classifier_params.h5"]
base_model_url: "https://github.com/GSPuniani/Fire-Detection-API-Project/releases/download/v1.0"
model_sha256: "31d25e5fb0edc3669318162173db46e049dfede7"
